### ISSUE TITLE
stream reading assembly is null - help needed

### ISSUE THREAD

**Issue by a1-games** [DaniloPeres/MonoGame.StrokeEffect#1] opened 2024-06-10 20:10 UTC
![image](https://github.com/DaniloPeres/MonoGame.StrokeEffect/assets/83002224/ee00395b-80f2-4f4a-afc9-39348a173d62)

I get this error when trying to use StrokeEffect.CreateStroke()
I've tried some googling but it's not something I've touched before. I have no idea how to fix it

![image](https://github.com/DaniloPeres/MonoGame.StrokeEffect/assets/83002224/2133c318-28d4-42d3-ac13-d3976ba99546)

**Comment by DaniloPeres** [comment] 2024-06-10 20:34
Hi,

In which platform are you working with? Android or UWP?

Also, this is an old version that only Monogame 3.8.0 works with it, which Monogame version are you using?

Later on I will try to upgrade to the new Monogame version

**Comment by a1-games** [comment] 2024-06-16 17:38
Sorry for not responding faster, I assumed I would get a notification about your comment

I'm making a Cross-Platform game 
![image](https://github.com/DaniloPeres/MonoGame.StrokeEffect/assets/83002224/daf0c225-3774-4d61-842e-c0576ef22f95)

with MonoGame 3.8.1.303
![image](https://github.com/DaniloPeres/MonoGame.StrokeEffect/assets/83002224/908bbebf-a508-4a7f-ae27-6769f173d987)

So I guess both are wrong. Unfortunate.

**Comment by DaniloPeres** [comment] 2024-06-17 20:30
Yeap, the problem is with the MonoGame version 3.8.1.303, my code still doesn't support this version.
Anyway, I still recommend you to keep on this MonoGame version, you can try to copy some code from this repo to create the same effects in your games, and maybe in the future I will update this code ;)

Good luck in your project and let me know if you have any question

**Comment by DaniloPeres** [comment] 2024-06-17 20:32
I am closing this issue, I hope to support the MonoGame version 3.8.1 soon

**Closed as not planned by DaniloPeres** 2024-06-17 20:32 UTC

**Comment by DaniloPeres** [comment] 2024-09-01 21:02
A new version Monogame 3.8.2.1105 and .net 8 has ben updated and not it should work just fine
